### ISSUE TITLE
Osa 1: XMLHttpRequest vs Fetch API

### ISSUE THREAD

**Issue by AhtiAhde** [mluukkai/mluukkai.github.io#11]
FullStack devaamisen suurimpia kipuja on ollut JavaScriptin callback hell-tyyliset ratkaisut. XHR on standardi vuosimallia 1999 ja Fetch on promisepohjainen ratkaisu vuosimallia 2014. Toki Fetch ei tue kaikkia selaimia vielä, mutta osittain kai siksi, ettei Microsoft enää oikein jaksa devata IE:tä, kun on Edge.

Siinä kohtaa, kun opiskelijat valmistuvat työelämään, uskon ettei Fetchin käytöstä ole haittaa ja lisäksi opiskelijat tottuisivat parempaan koodaustapaan (promiset, async / await) jo heti kättelyssä. Vaikka me olemme marssineet läpi callback helvetin, ei sen olemassa olosta välttämättä tarvitse uutta sukupolvea muistuttaa, kun ongelma alkaa pikkuhiljaa olemaan ratkaistu :)

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by mluukkai** [comment]
promiset ja fetch tai oikeastaan käytetään axioisia tulee osassa 2 kun aletaan tehdä itse requesteja async/await osassa 3 ensin backendissä

alun esimerkki käyttää XHR:ää koska en halua tuoda siihen vielä kompleksisuutta promisejen muodossa. ekassa osassa on muutenkin vaan eventteihin reagoimista, joten parempi hoitaa web-requestit samalla tavalla
