### ISSUE TITLE
Osa 1: Selvennystä HTTP POST + 302 käyttötapauksista

### ISSUE THREAD

**Issue by AhtiAhde** [mluukkai/mluukkai.github.io#12]
Kun koodataan esimerkiksi RESTful APIa vasten, on tyypillistä, että POST requestiin vastavaan 302:lla, koska RESTful paradigman mukaan, POST edustaa CRUD-periaatteen Createa.

Idea ei kuitenkaan ole siinä, että 302 sisältäisi POST bodyn, koska siitä ei ole mitään hyötyä HTTP protokollan käyttötarkoitusten näkökulmasta. Itseasiassa POST bodyn lähettäminen 302:n mukana on bugi ja HTTP-standardin vastainen ominaisuus.

Carnary Chromen tulkinta standardista on siis virheellinen, eikä kyseistä "bugia", jossa POST body tipahtaa pois 302:n jälkeen, tulla ikinä korjaamaan; HTTP-speksissä sanotaan "MUST NOT repost without user prompt".

POSTin tarkoituksena on oikean HTTP-semantiikan mukaan luoda uusi Unique Resource, ja jotta tähän uuteen resurssiin voitaisiin viitata, on 302 hyvä tapa vastata POST requestiin: Unique Resource vastaan otettu ja luotu, löydät sen tämän Unique Resource Identifierin (uri) takaa.

Fullstack devaamisessa olisi hyvä tuoda esiin tätä RESTful APIen maailmaa ja HTTP:n semantiikkaa CRUD pohjaisena protokollana. URI on siis eräänlainen pointteri ja POST requestin ei ole pakko aina vastata dataobjektilla (200 + JSON) vaan pointterikin käy.

Tämän vuoksi Preserve Logs täpän ruksittaminen on hyvä idea, koska jotkut RESTful palvelut käyttävät pointteritulkintaa oikeaoppisesta HTTPn käytöstä. Lisäksi sillä on tärkeä implikaatio: POST kyselyn vastaanottava palvelin ei voi tietää, onko lähetys duplikaatti. Jos normaalissa ohjelmassa suoritettaisiin Factory patternia, joka palauttaisi dataa referenssin sijaan, ei voitaisi laskea objektien määrää palautusarvojen perusteella ilman naivia oletusta, että koodissa ei ole virheitä.

Tämmöinen design patternikin on olemassa, kuin POST / REDIRECT / GET: https://en.wikipedia.org/wiki/Post/Redirect/Get

**Comment by mluukkai** [comment]
REST tulossa osassa 3

**Comment by AhtiAhde** [comment]
Liityen muuten tuohon bugiin, jonka mainitsit, niin olisiko jossain jotain helposti havaittavaa esimerkkiä siitä, että milloin normaali Chrome toimii "väärin"?

**Comment by mluukkai** [comment]
Chrome siis itsessään ei toimi väärin, ainoastaan konsolin
Network-välilehti, joka ei näytä POST:in mukana menevää dataa. Jotkut
aiemmat versiot näyttivät sen. Ja myös firefox näyttää datan. Ks liitteenä
olevat kuvat joissa kaikissa luodaan uusi muistiinpano sivulla
https://fullstack-exampleapp.herokuapp.com/notes


2017-12-16 15:32 GMT+02:00 Ahti Ahde <notifications@github.com>:

**Comment by mluukkai** [comment]
**canary chrome**

<img width="842" alt="canary" src="https://user-images.githubusercontent.com/523235/34072665-3214159e-e294-11e7-88d9-b351ae0ec0c1.png">

**chrome**

<img width="936" alt="chrome" src="https://user-images.githubusercontent.com/523235/34072666-323c589c-e294-11e7-9ca7-3f70087f3162.png">

**firefox**

<img width="1111" alt="firefox" src="https://user-images.githubusercontent.com/523235/34072667-3799a060-e294-11e7-8377-7bfe923b70dc.png">

**Comment by mluukkai** [comment]
jaha, kuvat eivät tulleet kun vastasin issueen mailitse

**Comment by AhtiAhde** [comment]
Muistaakseni Chrome näyttää POST requestin ihan oikein, mutta eripaikassa; testaan tässä POSTaamista (toivottavasti GitHubi käyttää POSTia)

**Comment by AhtiAhde** [comment]
Okei sain replikoitua; korjattu 6.12.2017 ;)

Huomasin myöskin, että puhuin status codesta 301, enkä 302... tai en oikein tiedä mistä se aiemmassa mailissa viittaamani kohta oli; tarkistin IANAn viralliset speksit ja niissä oli eri tavalla kirjoitettu. Jos backtrackasin virhepäätelmäni oikein, luin jotain speksiä ennen vuotta 2011, jonka joku oli linkannut samanlaiseen ongelmaan.

Tuossa on iso filosofinen ongelma HTTP-standardien kanssa ja varmaan siksi se mihin mailissa viittasin ei olekaan virallinen osa ainakaan nykyään. RESTful paradigman mukaan 302 on validi vastaus, mutta sinäänsä palvelimen ei pitäisi hyväksyä POST payloadia, jos redirectataan; toisaalta käytännössä taas tämä pätee ainoastaan 301:een, joka olettaa automaattista redirectiä tai sen mahdollisuutta, muttei välttämättä muihin redirecteihin.

Eli prosessi jossa POST requestiin vastataan 302, joka viittaa luotuun resurssiin on ihan validi ja Chromessa on tosiaan ollut bugi tuon suhteen versioissa 61 ja 62; aikaisemmin Chrome on kuulemma toiminut oikein, mokasivat kuulemma regressiotestauksessa.

Ehkä tämän eron korostaminen 301:den ja 302:den välillä kurssimateriaalissa voisi olla ihan jees (301 sisältää oletuksen, jossa client päivittää virheellisen linkin osoitteen), en toisaalta usko, että on niin relevantti asia.

**Comment by mluukkai** [comment]
Poistin nyt ehdotuksen canaryn käytöstä.

**Comment by AhtiAhde** [comment]
Kurssi alkaa sen verran pian, että on ehkä syytä mainita, että päivitys on
saapunut vasta hiljattain, ja myöskin toisinpäin, jollain voi olla vanha
versio joka toimii. Tiedottaminen ei ole pahasta.

18.12.2017 21.46 "Matti Luukkainen" <notifications@github.com> kirjoitti:

Poistin nyt ehdotuksen canaryn käytöstä.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mluukkai/mluukkai.github.io/issues/12#issuecomment-352537629>,
or mute the thread
