### ISSUE TITLE
Osa 1: SPA vs Pilvinatiivit sovellukset

### ISSUE THREAD

**Issue by AhtiAhde** [mluukkai/mluukkai.github.io#13]
Tässä SPA osiossa olisi ihan hauska mainita myös pilvinatiiveista sovelluksista, jotka eivät enää lähetä edes JSONia, vaan pelkät muutokset käsiteltävään URI viitteeseen. Vaikka pilvinatiivi fullstack devaaminen ei olisikaan tämän kurssin skopessa, olisi hauskaa näyttää opiskelijoille tämä trendi:

Staattiset sivulataukset -> dynaamiset sivulataukset -> SPA + RESTful, eli JSON lataukset -> pilvinatiivit pavelut, joissa lähetetään ainoastaan käyttäjän tekemät muutokset.

Yksi tapa ajatella tätä trendiä on tarkastella sitä, että kuka on käyttäjä:
Kukatahansa, jolla on linkki -> kuka tahansa + täysivaltaisempi HTTP-stäkin käyttö -> Selkeästi määritelty selain -> Selkeästi määritelty käyttäjä, jolla on selaimen lisäksi identiteetti (wallet).

EU:ssa GDPR lainsäädäntö tulee viemään palveluita enemmän Wallet tyylisen palvelutarjoilun suuntaan, koska ilman selkeästi määriteltyä Wallettia, EU:n kansalainen voi pyytää palveluntarjoajaa tuhoamaan tietoja, jotka ovat sotkeutuneet käyttäjän Walletin ulkopuoliseen dataan, mutta kuuluvat silti käyttäjälle.

Eli muutamalla sanalla ehkä hieman historiaa ja todennäköisiä tulevaisuuden trendejä. En tiedä yhtäkään pilvinatiivia tekstieditoria, joka ei toimisi muutoksia tallentamalla, vaan toimisi yhä RESTful + SPA arkkitehtuurilla.

**Comment by mluukkai** [comment]
ehdottoman hyvä idea, lisätään!
