### ISSUE TITLE
Osa 1: var, let ja const

### ISSUE THREAD

**Issue by AhtiAhde** [mluukkai/mluukkai.github.io#16]
Tässä kohtaa olisi ehkä hyvä avata, että miksi var on historiallisista syistä olemassa ja miten sen variable scope eroaa letistä.

**Comment by mluukkai** [comment]
joo, se pitää tuoda jossain kohtaa kurssia esille. en kuitenkaan viitsi ekalla viikolla kuormittaa liikaa. kenties linkki sopivaan paikkaan ois tossa hyvä niille jotka haluaa heti selvittää mistä kyse

**Comment by AhtiAhde** [comment]
Sinäänsähän tuo asia hoituisi aika yksinkertaisesti viittaamalla ehkä hieman ympäripyöreästi siihen, että var globaalissa scopessa toimii kuten muutamien muiden kielien global ja sitten ehkä parilla sanalla kertoa JavaScriptin scopeista hyvin yleisellä tasolla. Luulen että W3C:ltä saattaa jopa löytyä joku hyvä lause tai pari tätä varten.

Tärkeäähän on varmaan myöskin viitata siihen, että var alkaa olemaan hieman anti patterni, koska kaikkissa var use-caseissa myös let toimii; en ainakaan ole keksinyt mitään tilannetta, missä pitäisi käyttää varia letin sijaan ja sen sijaan on paljon tilanteita, joissa let on turvallisempi datan enkapsuloinnin näkökulmasta. Toki joskus voi haluta hieman "huijata" arkkitehtuuria injektoimalla dataa ohi funktio argumenttien, mutta en keksi miksi kukaan täysijärkinen devaaja näin haluaisi tehdä; hieman samaa kamaa kuin aneemiset funktiot -> epäturvallisia designin kannalta.
