### ISSUE TITLE
Osa1: Ubuntun paketinhallinnasta ja nvm:stä

### ISSUE THREAD

**Issue by AhtiAhde** [mluukkai/mluukkai.github.io#7]
Sanotaan: "Asenna koneeseesi heti myös Node.js. Materiaali on tehty versiolla 8.6, älä asenna mitään sitä vanhempaa versiota. Ubuntulla Node.js:ää todennäköisesti ei kannata asentaa pakettienhallinnasta eli apt-get:illä, sillä sieltä saatava versio on antiikkinen."

Jos en muista väärin, niin Ubuntulla asennettu NodeJS käyttää nvm:ää, jossa defaultti on 4.6 NodeJS ja latest stable on NodeJS 8.6; eli nvm:llä on kätevää vaihtaa käytössä olevan Noden versiota. Tämän olen testannut Googlen pilvessä Ubuntu 16.04 imagea vastaan pari viikkoa sitten työelämässä; jos siis muistini ei ole petollinen tässä kohtaa. Usein nykyään NodeJS tulee nvm:än kanssa ja vanha defaultti versio on ihan yleinen juttu.

**Comment by mluukkai** [comment]
Pitäisikin lisätä joku dokumentti, minne voisi laittaa ohjeita ympäristön setuppaukseen

**Comment by mluukkai** [comment]
Asennusohjeita varten lisätty kaikkien editoitavissa oleva https://github.com/mluukkai/mluukkai.github.io/wiki/asennusohjeita
