### ISSUE TITLE
Osa1: Kehitysympäristön valinta

### ISSUE THREAD

**Issue by AhtiAhde** [mluukkai/mluukkai.github.io#8]
Sanotaan: "Asenna myös joku järkevä webkoodausta tukeva tekstieditori, enemmän kuin suositeltava valinta on Visual studio code. Myös Atom on tarkoitukseen toimiva.

Älä koodaa nanolla, notepadilla tai geditillä. Netbeanskaan ei ole omimmillaan Web-koodauksessa ja se on myös turhan raskas verrattuna esim. Visual Studio Codeen."

Yksi varteen otettava vaihtoehto on pilvinatiivi Cloud 9, jonka opetuslisenssi ei vaadi opiskelijalta luottokorttia.

Pilvinatiivilla kehitysympäristöllä on helpompaa testata HTTPS:ää, sekä joidenkin thirdparty paveluiden (esim. Googlen OAuth2.0) käyttöä, jotka vaativat oikean top-level domainin toimiakseen. Toki Cloud 9 vaatii vanhoilta devaajilta hieman totuttelua, kun paradigma on erilainen.

Itse olen devannut Cloud 9:llä jo yli kaksi vuotta, koska Dockerisoinnit ovat usein "ongelmattomia", mutta käytännössä Windows koneilla ne eivät toimi ja Macillä imaget menee rikki käyttöjärjestelmäpäivitysten yhteydessä. Lisäksi viimeisimmässä projektissa, jossa olen tehnyt Micro Service + Micro Frontend tyylistä systeemiä, Dockerin imagejen buildaamiseen menee yli 11 minuuttia ja käynnistämiseen hieman yli minuutti -> oikean imagen devaaminen on helpompaa ja kivempaa ja jos Dockeria on pakko käyttää, on hyvä, että se jää päälle virtuaalipalvelimelle, koska läppärin joutuu aina työpäivän päätteeksi sammuttamaan (hibernation tilat ja muut "väärin sammutukset" saattavat korruptoida Docker containerit, jolloin pitää tehdä rebuildi).

Cloud 9 on tuntunut yhtä hyvältä Docker + Mac kombon jälkeen, kuin Golang NodeJS:än jälkeen, eli ero on massiivisen mukava, kun asiat vaan toimii oikeasti, eikä leikisti.

**Comment by mluukkai** [comment]
pitääkin lisätä tuo, itse en ole Cloud 9:ää edes kokeillut.
