### ISSUE TITLE
Osa1: Oppimistavoitteet; Autentikaatiosta voisi sanoa pari sanaa

### ISSUE THREAD

**Issue by AhtiAhde** [mluukkai/mluukkai.github.io#9]
Signed Cookies tyyliset ratkaisut ovat tulleet jäädäkseen, joten OAuth 2 yms. autentikaatio prosessit, sekä signed cookieiden varaan rakentuvat tavat jakaa salaista dataa webissä, ovat tärkeä osa nykyaikaista Full-Stack devaamista, etenkin pilvinatiiveissa projekteissa.

Esimerkiksi elokuva-alalla suunnitellaan tiedostoformaatteja, jotka perustuvat security certificate providereihin, sekä palvelimiin, joilla on lupa jaella käyttäjille signed-cookieita, sekä lisäksi CDN + AWS S3 tai GCS palveluun, joka sisältää adaptiiviset striimitiedostot, jotka dekoodaantuu ainoastaan certin ja signed-cookien yhdistelmällä (eli hieman samaan tapaan kuin public ja pricate key jutut).

Toki tämä saattaisi istua paremmin osaan 6.

**Comment by mluukkai** [comment]
hyviä pointteja. tulevat myöhempään osaan.
